# Generated by Django 4.2.6 on 2023-10-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rent_price',
            field=models.IntegerField(),
        ),
    ]
