# Generated by Django 4.2.6 on 2023-10-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_booking_bookingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='service_area_to',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
