# Generated by Django 4.2.6 on 2023-10-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_car_service_area_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
